# Generated by Django 5.0.4 on 2024-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_poll_question_question_text_alter_choice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls_images/'),
        ),
    ]
